version: "3.8"
services:
  db:
    image: postgres:14.9
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.data:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'

volumes:
  db_data:

